### ISSUE TITLE
Currency toggle on send screen is not two way bounded.

### ISSUE THREAD

**Issue by jayrulez** [SenitCorp/bugtracker#83] opened 2018-09-13 20:37 UTC
If I toggle the send currency the currency of the account balance also changes.

When I toggle the account balance currency the send currency does not change.

Not sure if the is the desired behaviour but it seems a bit strange.

**Comment by jayrulez** [comment] 2018-09-13 20:38
@senit comment?

**Comment by Ibar000** [comment] 2018-09-13 20:55
Robert, 
I believe this behaviour to be by design.  Jovi reports that the iOS client behaves the same way.
Regards

**Comment by Ibar000** [comment] 2018-09-19 21:02
fixed on Android

**Closed as completed** 2018-10-05 04:34 UTC
Labels: question, Android
