### ISSUE TITLE
new users address book listing not showing new trasnactions

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#154] opened 2018-10-31 23:33 UTC
i.	cant see new transaction in contact history for new contacts –ok.
1.	create new user 
2.	send user funds
3.	transaction not showing up in address page contact history for new user

**Comment by jovi959** [comment] 2018-10-31 23:59
might be the same bug #139

**Comment by tajwane** [comment] 2018-11-01 22:14
Duplicate of #139

**Closed as completed by tajwane** 2018-11-01 22:14 UTC
Labels: Android, High Priority
